# Generated by Django 5.0.4 on 2024-06-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='customer_email',
            new_name='correo_solicitante',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='customer_name',
            new_name='nombre_solicitante',
        ),
        migrations.RenameField(
            model_name='pedidoorden',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='pedidoorden',
            old_name='order',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='pedidoorden',
            old_name='product',
            new_name='producto',
        ),
    ]
