# Generated by Django 5.0.4 on 2024-06-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_customer_email_pedido_correo_solicitante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='correo_solicitante',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_solicitante',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='pedidoorden',
            old_name='pedido',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='pedidoorden',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='pedidoorden',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
