# Generated by Django 5.0.4 on 2024-06-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('apellido_cliente', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('telefono_cliente', models.CharField(max_length=15, verbose_name='Teléfono del Cliente')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo')),
                ('asunto_cliente', models.CharField(max_length=100, verbose_name='Asunto')),
                ('mensaje_cliente', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactanos',
            },
        ),
        migrations.CreateModel(
            name='InformacionPagina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('informacion', models.CharField(max_length=300, verbose_name='Información de la página Web')),
                ('acerca', models.TextField(verbose_name='Acerca de la página Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Informacion de la Pagina Web',
                'verbose_name_plural': 'Informacion de la Pagina Web',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_de_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_de_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
    ]
